
security:
  argon2:
    type: ARGON2d      # ARGON2i, ARGON2d 或 ARGON2id
    iterations: 2        # 迭代次数
    memory: 65536        # 内存使用量(KB)
    parallelism: 4       # 并行度

spring:
  application:
    name: Hrcs-Starter
  mail:
    username: yu_hl0v1@163.com
    password: DBdBG33giK2kLwaD
    host: smtp.163.com
  datasource:
    url: jdbc:mysql://localhost:3306/customer_service?useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      database: 0
      host: localhost
      port: 6379
      lettuce:
       pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
        max-wait: -1ms



springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.yyds.hrcsserver.**.controller
knife4j:
  enable: true
  setting:
    language: zh_cn


mybatis-plus:
  configuration:

    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


server:
  port: 8024




